### ISSUE TITLE
最近出现扫描途中卡死的问题

### ISSUE THREAD

**Issue by FolStone** [yzwduck/FontLoaderSub#1]
https://cdn.sinaimg.cn.52ecy.cn/large/005BYqpgly1g3mqg7wi1gj309x05fq2v.jpg
某次加载新字幕时卡死，之后再试即使删除db文件还是一样卡死，是不是某个字体文体安装时出错？

**Comment by FolStone** [comment]
最后证实应该是某个沙雕软件占用了其中一个字体，但是占用字体为何就会报错……

**Comment by yzwduck** [comment]
之前也有人报告过类似的问题，今天又查了一下代码，发现在文件打开时，有一个判断条件写错了，很可能是这类崩溃的罪魁祸首。
610d7dbca0bf2072f8181ac1bdab2c9ba7dbddef 大概修正了这个问题。

**Comment by FolStone** [comment]
> 之前也有人报告过类似的问题，今天又查了一下代码，发现在文件打开时，有一个判断条件写错了，很可能是这类崩溃的罪魁祸首。
> [610d7db](https://github.com/yzwduck/FontLoaderSub/commit/610d7dbca0bf2072f8181ac1bdab2c9ba7dbddef) 大概修正了这个问题。

= = 代码什么的，等一个正式更新吧，辛苦了

**Comment by yzwduck** [comment]
正式的更新很可能还要过几个月…如果经常遇到这个问题的话，可以去 https://ci.appveyor.com/project/yzwduck/fontloadersub 的 artifacts 找最新的编译版本试试。

**Comment by zhaocai** [comment]
`r4` 能用，`r5`不行。重启之后一样。

**Comment by yzwduck** [comment]
@zhaocai 能否用上面 appveyor 链接中的版本测试一下？
在没有使用字幕的情况下、扫描字体文件夹的过程中是否还会卡死（崩溃）？

**Comment by zhaocai** [comment]
@yzwduck 试过，和r5一样。有没有加载字幕没区别，都是扫描过程中卡死。

**Comment by FolStone** [comment]
> 正式的更新很可能还要过几个月…如果经常遇到这个问题的话，可以去 https://ci.appveyor.com/project/yzwduck/fontloadersub 的 artifacts 找最新的编译版本试试。

确认过这个版本也会卡死……所以说为啥被别的程序占用的字体会导致卡死呢……

**Comment by yzwduck** [comment]
程序表面上卡死，实际上是崩溃了。如果可以的话，能否提供一份 crash dump 来分析程序在你电脑环境中遇到的问题？具体步骤：
1. 修改注册表，在 `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps` 中，把 `DumpType` 改为 2（如果不存在，则创建这个 DWORD 类型的键值）；
2. 让程序崩溃，此时会在 `C:\Users\<用户名>\AppData\Local\CrashDumps` 下面生成一个 dmp 文件；
3. 将 dmp 文件，和程序生成的 fc-subs.db（如果有）一起**加密**压缩后，把网盘链接/作为附件发我邮箱，最好附上程序的 md5/sha1 或任意哈希值；
4. 把注册表还原。

**Comment by FolStone** [comment]
> 程序表面上卡死，实际上是崩溃了。如果可以的话，能否提供一份 crash dump 来分析程序在你电脑环境中遇到的问题？具体步骤：
> 
> 1. 修改注册表，在 `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps` 中，把 `DumpType` 改为 2（如果不存在，则创建这个 DWORD 类型的键值）；
> 2. 让程序崩溃，此时会在 `C:\Users\<用户名>\AppData\Local\CrashDumps` 下面生成一个 dmp 文件；
> 3. 将 dmp 文件，和程序生成的 fc-subs.db（如果有）一起**加密**压缩后，把网盘链接/作为附件发我邮箱，最好附上程序的 md5/sha1 或任意哈希值；
> 4. 把注册表还原。

= =但是并没有对应dmp文件生成

**Comment by yzwduck** [comment]
没有 dmp 的话，程序应该只是卡死了，而没有崩溃。
这时可以在任务管理器里找到进程，右键菜单里有一个“创建转储文件/Create dump file”，（但愿）能用来分析故障原因。
文件体积会比较大，如需传输，推荐使用 **加密** 压缩。
