### ISSUE TITLE
能否设置在关闭程序后不卸载字体呢

### ISSUE THREAD

**Issue by LoneFireBlossom** [yzwduck/FontLoaderSub#2]
首先十分感谢发布者，这个程序省去了我一个一个搜字体然后手动安装的麻烦，而且不用为了一个字体多个名称，搜不到而发愁了。
我的想法是，如果看动画的时间比较零碎（比如我），那么每次打开动画之前都要进行一次把字幕拖到程序上的操作，感觉这样挺麻烦。而且我个人的习惯是，只要遇到字幕需要的字体就安装上，不会将其卸载掉（除非是VCB包中“慎用”文件夹中的字体）。目前Fonts文件夹里有1500左右的字体了，使用Office等软件也没有什么不便，就是第一次打开字体下拉菜单时需要等两秒（i5-8250U），所以感觉只要字幕组是比较有名的，使用的字体一般都比较正规，安装了这些字体应该也不会出啥BUG。
因此，希望您如果有精力的话，可以考虑一下加上“关闭程序不卸载字体”的功能。无论是给个打钩的框，还是在打开程序时弹出对话框选择，还是按关闭就是卸载字体、按Alt+F4/任务管理器中强制结束任务就不卸载字体，还是提供两个程序一个关闭后卸载另一个关闭后不卸载，还是其它的都好，总之十分感谢！

**Comment by yzwduck** [comment]
因为不卸载字体会占用字体文件，卸载字体只有通过API或重启才能实现，对于大部分用户而言自行卸载的难度很大，实用性有限（其实因为界面空间有限），所以我不打算在程序中添加这个选项；
但如果想关闭程序而不卸载字体的话，其实可以用任务管理器强制结束任务，这样做的话，临时加载的字体会保持加载的状态，直到电脑关机或重启。
如果觉得将字幕拖到程序上比较麻烦的话，可以试试建立快捷方式：直接运行程序，就可以看到快捷方式的管理入口。

**Comment by LoneFireBlossom** [comment]
谢谢回复。
好的，我试试。

> 但如果想关闭程序而不卸载字体的话，其实可以用任务管理器强制结束任务，这样做的话，临时加载的字体会保持加载的状态，直到电脑关机或重启。

这个我之前就试过；这次又试了一遍，在任务管理器中右键菜单选择“结束任务”的话，可以看到程序是又执行了一小会儿才关闭的（任务栏上的该程序有进度条的“波”），猜测是执行了卸载字体的命令。
结果上也是如此，
之前尝试的时候使用potplayer+xysubfilter，使用任务管理器结束该程序任务的话，再打开视频与字幕，字幕的字体就变成很丑的样子了；
这次又尝试potplayer+xysubfilter，使用任务管理器结束该程序任务后，无论打开有没有字幕的视频，potplayer都死了。换用MPC-BE尝试，字幕的字体也是变成很丑的样子。

**Comment by yzwduck** [comment]
emm...我用的是英文的界面，所以表述和中文界面的 Windows 有点出入，修正一下：
应该去任务管理器的“详细信息”里，找到 FontLoaderSub.exe，然后把它结束任务。这样程序就没有机会执行清理工作，临时加载的字体会被保留。

**Comment by LoneFireBlossom** [comment]
谢谢回复，的确如此。

**Comment by RtYkk** [comment]
原来两年前就有人提过……还好没有直接开新的，感觉有一点遗憾，我先试试看上面的方法吧。
