### ISSUE TITLE
Not Compatible with Netease MuMu Android Simulator

### ISSUE THREAD

**Issue by FlyGinger** [yzwduck/FontLoaderSub#4]
Recurrence:
1. System: Windows 1903, 18362.
2. Start Netease MuMu Android Simulator (v2.2.15).
3. Start FontLoaderSub.

The fonts are successfully loaded, but the fontloadersub will be stuck in "No Response" status until the Netease MuMu Android Simulator is closed.

**Comment by yzwduck** [comment]
Can you try with the latest build at [AppVeyor](https://ci.appveyor.com/project/yzwduck/fontloadersub/build/artifacts) ?
It seems like a known issue, which is fixed at 00767d7fc77c1d546166a82455e3c0c8eef34548 .
