### ISSUE TITLE
Truetype fonts export 

### ISSUE THREAD

**Issue by louy2099** [yzwduck/FontLoaderSub#5]
Hello yzwduck thank you for your work, i'm wondering if it's possible to extract Truetype fonts as well as OpenType fonts

**Comment by yzwduck** [comment]
Hi louy2099, I'm not quite clear with what you mean by the word "extract".
This tool does not support extracting embedded fonts in ASS files, nor does it read media containers (such as mkv). But it does have an "export" function which will copy all files shown in the dialog to a folder you choose.

**Comment by louy2099** [comment]
Yes i understand that , i have an ASS files that uses  Truetype fonts and OpenType fonts i put the tool in my fonts folder when i drag the ASS files to the tool it detect all Truetype fonts and OpenType fonts but when i hit export to a new folder it only export OpenType fonts

**Comment by louy2099** [comment]
Sorry my mistake , the tool need to be closed before open it again and load a new files
